# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mF1LfWk0UaDupmAR2oJKsyslrZqyHYjW
"""

import streamlit as st
import pandas as pd
import random

# === READ CSV ===
@st.cache_data
def read_csv_to_dict(file):
    df = pd.read_csv(file)
    program_ratings = {}
    for i, row in df.iterrows():
        program_ratings[row[0]] = [float(x) for x in row[1:]]
    return program_ratings, df.columns[1:]

# === STREAMLIT INTERFACE ===
st.title("📺 TV Program Scheduling using Genetic Algorithm")

uploaded_file = st.file_uploader("📂 Upload modified_program_ratings.csv", type="csv")
if uploaded_file:
    ratings, time_slots = read_csv_to_dict(uploaded_file)
    all_programs = list(ratings.keys())
    all_time_slots = list(range(len(time_slots)))

    # === PARAMETERS ===
    st.sidebar.header("⚙️ Genetic Algorithm Parameters")
    CO_R = st.sidebar.slider("Crossover Rate (CO_R)", 0.0, 0.95, 0.8)
    MUT_R = st.sidebar.slider("Mutation Rate (MUT_R)", 0.01, 0.05, 0.02)
    GEN = 100
    POP = 50
    EL_S = 2

    # === FITNESS FUNCTION ===
    def fitness_function(schedule):
        total = 0
        for i, program in enumerate(schedule):
            total += ratings[program][i]
        return total

    # === INITIALIZE ===
    def initialize_population(programs, size):
        return [random.sample(programs, len(programs)) for _ in range(size)]

    # === CROSSOVER ===
    def crossover(s1, s2):
        point = random.randint(1, len(s1)-2)
        return s1[:point] + s2[point:], s2[:point] + s1[point:]

    # === MUTATE ===
    def mutate(schedule):
        new = schedule.copy()
        i = random.randint(0, len(schedule)-1)
        new[i] = random.choice(all_programs)
        return new

    # === GENETIC ALGORITHM ===
    def genetic_algorithm():
        population = initialize_population(all_programs, POP)
        for _ in range(GEN):
            population = sorted(population, key=fitness_function, reverse=True)
            new_pop = population[:EL_S]
            while len(new_pop) < POP:
                p1, p2 = random.choices(population[:10], k=2)
                if random.random() < CO_R:
                    c1, c2 = crossover(p1, p2)
                else:
                    c1, c2 = p1.copy(), p2.copy()
                if random.random() < MUT_R:
                    c1 = mutate(c1)
                new_pop.extend([c1, c2])
            population = new_pop
        return max(population, key=fitness_function)

    if st.button("🚀 Run Genetic Algorithm"):
    best_schedule = genetic_algorithm()
    total_rating = fitness_function(best_schedule)

    # ✅ Fix for unequal lengths
    min_length = min(len(time_slots), len(best_schedule))
    time_slots = list(time_slots)[:min_length]
    best_schedule = best_schedule[:min_length]

    result_df = pd.DataFrame({
        "Hour": time_slots,
        "Program": best_schedule
    })

    st.subheader("📋 Optimal Schedule")
    st.table(result_df)
    st.write(f"**Total Rating:** {total_rating:.2f}")
